### ISSUE TITLE
化身孤岛的鲸

### ISSUE THREAD

**Issue by ccwhale** [ccwhale/OneDay#1]
我未入过繁华之境
未听过喧嚣的声音
未见过太多生灵
未有过滚烫心情
所以也未觉大洋正中
有多么安静

  每天最孤独的时候是下班回去的时候，看着路灯和宽阔的马路，最近听到的这首歌，感觉泪就要出来了。我的性格就是如此，不擅长交朋友，男生或是女生都是如此，新来的两个妹子看起来很快就熟络了，我却没跟她们说过话，我可以找个借口说，我跟徐腾飞也基本没说过话啊这样的借口，不做相同的工作也没什么话可以说这样的借口来掩饰自己拒绝交朋友的内心。如果真的是本性使然，那就要学会真正独立生活呀，不要抱怨自己老是一个人了，看来只适合生活在电脑后面。今天希哥说相亲的时候自拍和宠物照会降低对方的好感率，大前提不满足，我现在不需要相亲。也许几年之后，我会把我的社交网络的头像都换成能给对方好感的，为了相亲new对象吧。
  我晚上要看权利的游戏了，因为今天不用写日报呀。

我路过太多太美的奇景
如同伊甸般的仙境
而大海太平太静
多少故事无人倾听
我爱地中海的天晴
爱西伯利亚的雪景
爱万丈高空的鹰
爱肚皮下的藻荇
我在尽心尽力地多情

**Comment by bingoohuang** [comment]
哈哈，这种歌，可以偶尔听听，听多了总感觉无病呻吟。那么多感伤，那么多多情，分一份给工作，分一份给朋友，留一份给自己就行了。

**Comment by ccwhale** [comment]
issue的功能让我想起了国际的dmp平台～哈哈嗯咯我要学会唱这首歌啊。
